# Generated by Django 5.2.7 on 2026-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometrics", "0002_webauthncredential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biometrictemplate",
            name="nose_features",
            field=models.JSONField(
                blank=True, default=list, help_text="MediaPipe nasal landmark vector"
            ),
        ),
        migrations.AlterField(
            model_name="biometrictemplate",
            name="thumb_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional ICA thumbprint vector (Windows Hello handles fingerprint)",
            ),
        ),
    ]
