"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hp*4y_dki-bb7t4e3z*(bn3hhhx^9gs@7ad)5yvl57q*=j@!u+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps (python manage.py startapp <name>)
    "accounts.apps.AccountsConfig",
    "catalog.apps.CatalogConfig",
    "circulation.apps.CirculationConfig",
    "biometrics.apps.BiometricsConfig",
]

MIDDLEWARE = [
    "config.middleware.LocalhostWebAuthnMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

TIME_ZONE = "Africa/Lagos"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

LIBRARY_LOAN_DAYS = 14

# Multimodal biometrics (face + nose MediaPipe + thumb ICA + k-NN thresholds)
BIOMETRIC_FACE_THRESHOLD = 22.0
BIOMETRIC_NOSE_THRESHOLD = 12.0
BIOMETRIC_THUMB_THRESHOLD = 6.0
BIOMETRIC_REQUIRE_ENROLLMENT_TO_BORROW = True

# Nose liveness (multi-frame + visibility + blink)
BIOMETRIC_LIVENESS_MIN_FRAMES = 3
BIOMETRIC_LIVENESS_MIN_VISIBILITY = 0.40
BIOMETRIC_LIVENESS_MIN_MOVEMENT = 0.8
BIOMETRIC_LIVENESS_MAX_MOVEMENT = 120.0
BIOMETRIC_LIVENESS_MAX_STATIC_SIMILARITY = 0.25
BIOMETRIC_LIVENESS_MAX_FACE_STATIC_SIMILARITY = 0.20
BIOMETRIC_LIVENESS_MIN_BLINK_DELTA = 0.012
BIOMETRIC_LIVENESS_MIN_MOUTH_DELTA = 0.04
BIOMETRIC_LIVENESS_MIN_Z_SPREAD = 0.006

# Windows Hello via WebAuthn — RP ID / origin are taken from the browser URL automatically.
# Leave WEBAUTHN_RP_ID and WEBAUTHN_ORIGIN unset unless deploying to production.
WEBAUTHN_RP_NAME = "LAUTECH Library"
# WEBAUTHN_RP_ID = None
# WEBAUTHN_ORIGIN = None
